[project]
name = "tomnut-dima"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets==3.1.0",
    "numpy==2.1.3",
    "torch==2.5.1",
    "tqdm==4.67.0",
    "transformers==4.46.2",
    "wandb==0.18.7",
]
